server:
  port: 8060

spring:
  application:
    name: census-fwmt-csvservice
  jackson:
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false
  security:
    user:
      name: "user"
      password: "password"

management:
  # Place /info and /health in the root
  endpoints.web.base-path: ''
  endpoint:
    health:
      show-details: always

logging:
  level:
    root: WARN
    uk.gov.ons.census.fwmt: INFO
    org.springframework.security: INFO
    org.springframework.web: INFO
    org.springframework.amqp: INFO
    org.hibernate: INFO
    org.apache.commons.dbcp2: INFO
    org.springframework: INFO

rabbitmq:
  username: "guest"
  password: "guest"
  hostname: "localhost"
  port: 5672
  virtualHost: "/"
  initialinterval: 5000
  multiplier: 3.0
  maxInterval: 45000

gcpBucket:
#  celocation: "gs://csv-bucket-test/ceTestCSV.csv"
#  ccslocation: "gs://csv-bucket-test/ccsTestCSV.csv"
#  addresschecklocation: "gs://csv-bucket-test/AC.csv"
#  postcodelookuplocation: "gs://csv-bucket-test/addressLookup.csv"
#  directory: "gs://csv-bucket-test/"

  celocation: "ile://${home}/acceptance/data/ceTestCSV.csv"
  ccslocation: "file://${home}/acceptance/data/ccsTestCSV.csv"
  addresschecklocation: "file://${home}/acceptance/data/AC.csv"
  postcodelookuplocation: "file://${home}/acceptance/data/addressLookup.csv"
  directory: "file://${home}/acceptance/data/"